version: '3'
services:
  clubhouse-service-dev:
    container_name: clubhouse-service-dev
    image: odjhey/clubhouse-service:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: 'node server.js'
    ports:
      - '3790:8080'
    environment:
      PORT: '8080'
